#!/usr/bin/env python3
"""Pre-render the glyphs the firmware needs into an A8 atlas (C source).

Collects every character that appears in string literals of the slime_core
and main sources, plus printable ASCII, and renders them at 14/18/22 px.

The font is Noto Sans SC (SIL Open Font License 1.1, https://fonts.google.com/noto/specimen/Noto+Sans+SC);
the generated bitmaps are distributed under the same license, see THIRD_PARTY.md. It only ships
in Regular, so each glyph is drawn at 4x with a thin stroke and scaled down: about a quarter pixel
of extra weight, which reads better on the small screen.

Usage: python3 tools/gen_glyphs.py [path/to/NotoSansSC.ttf]   (needs Pillow; or set SLIME_FONT)
"""
import math
import os
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "components" / "slime_core"
OUT = CORE / "slime_glyphs.c"
OUT_EXT = CORE / "slime_glyphs_ext.c"
EXT_SIZE_INDEX = 2  # the extension table: 22 px only (the dialog's main line)
FONT_CANDIDATES = [
    "~/Library/Fonts/NotoSansSC.ttf",
    "/Library/Fonts/NotoSansSC.ttf",
    "/usr/share/fonts/truetype/noto/NotoSansSC-Regular.ttf",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
]
SIZES = [14, 18, 22]  # matches sl_font_t order
SUPER = 4  # supersampling factor
STROKE = 1  # at SUPER x: 0.25 px of extra weight


def find_font():
    for p in [*sys.argv[1:2], os.environ.get("SLIME_FONT", ""), *FONT_CANDIDATES]:
        p = os.path.expanduser(p)
        if p and os.path.isfile(p):
            return p
    sys.exit("Noto Sans SC not found: download it (OFL) and pass its path, or set SLIME_FONT")


def render(font_big, ch, size):
    """Bitmap (bytes), its offset from the pen position on the baseline, and its size."""
    pad = size * SUPER
    img = Image.new("L", (pad * 3, pad * 3), 0)
    ox0, oy0 = pad, pad * 2  # origin, a multiple of SUPER so the cell grid lines up
    ImageDraw.Draw(img).text((ox0, oy0), ch, font=font_big, fill=255, anchor="ls",
                             stroke_width=STROKE, stroke_fill=255)
    box = img.getbbox()
    if not box:
        return b"", 0, 0, 0, 0
    x0 = math.floor(box[0] / SUPER) * SUPER
    y0 = math.floor(box[1] / SUPER) * SUPER
    x1 = math.ceil(box[2] / SUPER) * SUPER
    y1 = math.ceil(box[3] / SUPER) * SUPER
    w, h = (x1 - x0) // SUPER, (y1 - y0) // SUPER
    small = img.crop((x0, y0, x1, y1)).resize((w, h), Image.BOX)
    return small.tobytes(), (x0 - ox0) // SUPER, (y0 - oy0) // SUPER, w, h

# sources whose Chinese is never drawn by the pet itself (Home Assistant shows those entity names)
NOT_ON_SCREEN = {"ha_mqtt.c"}
LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')


def collect_chars():
    chars = {chr(c) for c in range(32, 127)}
    for src in sorted(CORE.glob("*.c")) + sorted((ROOT / "main").glob("*.c")):
        if src.name == OUT.name or src.name in NOT_ON_SCREEN:
            continue
        for lit in LITERAL.findall(src.read_text(encoding="utf-8")):
            chars.update(ch for ch in lit if ord(ch) >= 0x80)
    return sorted(chars, key=ord)


def gb2312_level1():
    """The 3755 most common Chinese characters (GB2312 level 1, rows 16-55)."""
    out = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                out.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return out


def write_ext(path, have):
    """Dynamic text (the pet's AI comments) can use any common character: a 4-bit table of the
    GB2312 level-1 set at 22 px, for whatever the main atlas does not already hold."""
    size = SIZES[EXT_SIZE_INDEX]
    font = ImageFont.truetype(path, size)
    big = ImageFont.truetype(path, size * SUPER)
    glyphs, data = [], bytearray()
    for ch in sorted(set(gb2312_level1()) - have, key=ord):
        bits, ox, oy, w, h = render(big, ch, size)
        off = len(data)
        nib = [(b * 15 + 127) // 255 for b in bits]
        if len(nib) % 2:
            nib.append(0)
        data.extend((nib[i] << 4) | nib[i + 1] for i in range(0, len(nib), 2))
        glyphs.append((ord(ch), EXT_SIZE_INDEX, ox, oy, w, h, round(font.getlength(ch)), off))
    lines = [
        "/* Generated by tools/gen_glyphs.py - do not edit. 4 bits per pixel, high nibble first. */",
        '#include "slime_text.h"',
        "",
        "const sl_glyph_t sl_glyphs_ext[] = {",
    ]
    lines += [f"    {{0x{cp:04x}, {fi}, {ox}, {oy}, {w}, {h}, {adv}, {off}}}," for cp, fi, ox, oy, w, h, adv, off in glyphs]
    lines += ["};", f"const int sl_glyph_ext_count = {len(glyphs)};", "", "const uint8_t sl_glyph_a4[] = {"]
    for i in range(0, len(data), 32):
        lines.append("    " + ",".join(str(b) for b in data[i : i + 32]) + ",")
    lines += ["};", ""]
    OUT_EXT.write_text("\n".join(lines), encoding="utf-8")
    print(f"extension: {len(glyphs)} glyphs at {size} px, {len(data)} bytes -> {OUT_EXT}")


def main():
    chars = collect_chars()
    glyphs, data = [], bytearray()
    path = find_font()
    for fi, size in enumerate(SIZES):
        font = ImageFont.truetype(path, size)
        big = ImageFont.truetype(path, size * SUPER)
        for ch in chars:
            bits, ox, oy, w, h = render(big, ch, size)
            adv = round(font.getlength(ch))
            off = len(data)
            data.extend(bits)
            glyphs.append((ord(ch), fi, ox, oy, w, h, adv, off))
    glyphs.sort(key=lambda g: (g[1] << 24) | g[0])

    lines = [
        "/* Generated by tools/gen_glyphs.py - do not edit. */",
        '#include "slime_text.h"',
        "",
        "const sl_glyph_t sl_glyphs[] = {",
    ]
    for cp, fi, ox, oy, w, h, adv, off in glyphs:
        lines.append(f"    {{0x{cp:04x}, {fi}, {ox}, {oy}, {w}, {h}, {adv}, {off}}},")
    lines += ["};", f"const int sl_glyph_count = {len(glyphs)};", "", "const uint8_t sl_glyph_a8[] = {"]
    for i in range(0, len(data), 24):
        lines.append("    " + ",".join(str(b) for b in data[i : i + 24]) + ",")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    cjk = [c for c in chars if ord(c) >= 0x80]
    print(f"{len(chars)} chars ({len(cjk)} non-ASCII), {len(glyphs)} glyphs, {len(data)} bytes -> {OUT}")
    write_ext(path, set(chars))


if __name__ == "__main__":
    main()
