#!/usr/bin/env python3
"""Write the esp-dl "compile request" for the face detector.

esp-dl compiles every operator unless some component asks for a subset; esp-sr (the wake word)
does ask, for its own models only, and the face detector's model then fails to load. This
adds the operators the face models use, so esp-dl keeps just the union: about 1.5 MB less
firmware than compiling everything.

Conv kernels are requested by name too, and they are most of esp-dl's size. The face models
are 8-bit ("s8"), so every 8-bit kernel the installed esp-dl knows is requested and the 16-bit
ones are left to whoever needs them (esp-sr lists its own). A missing kernel does not fail
loudly, the layer just produces nothing and no face is ever found: after changing this, check
on the device that faces are still detected.

Usage: gen_espdl_req.py <esp-dl>/spec/kernels.yml <out.yml>
Called from the project CMakeLists.txt. When the face models change, update FACE_OPS: they are
the operator names found in the .espdl files (human_face_detect_msr_s8_v1, ..._mnp_s8_v1).
"""
import re
import sys

FACE_OPS = ["Concat", "Conv", "PRelu", "Relu"]
# espdet_pico_224_224_hand and mobilenetv2_0_5_128_128_gesture
HAND_OPS = ["Add", "Concat", "Conv", "Flatten", "Gemm", "GlobalAveragePool", "MaxPool", "Relu", "RequantizeLinear", "Resize",
            "Split", "Transpose"]


def main():
    kernels_yml, out = sys.argv[1:3]
    with open(kernels_yml, encoding="utf-8") as f:
        text = f.read()
    abi = re.search(r"^kernel_abi:\s*(\d+)", text, re.M).group(1)
    symbols = [k for k in re.findall(r"^\s+-\s+(dl_\w+)\s*$", text, re.M) if "_s8_" in k]
    lines = ["# Generated by tools/gen_espdl_req.py - do not edit.", "kernel_abi: %s" % abi, "", "ops:"]
    lines += ["  - %s" % op for op in sorted(set(FACE_OPS + HAND_OPS))]
    lines += ["", "kernels:"] + ["  - %s" % s for s in symbols]
    new = "\n".join(lines) + "\n"
    try:
        with open(out, encoding="utf-8") as f:
            if f.read() == new:
                return  # unchanged: do not retrigger the build
    except OSError:
        pass
    with open(out, "w", encoding="utf-8") as f:
        f.write(new)


if __name__ == "__main__":
    main()
