/*
 * Pre-rendered glyph atlases (generated by tools/gen_glyphs.py) + UTF-8 text drawing.
 */
#pragma once

#include <stdint.h>

#include "sg.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { SL_FONT_14 = 0, SL_FONT_18, SL_FONT_22, SL_FONT_COUNT } sl_font_t;

/* UI language, set by the firmware from its settings. English text sticks to printable ASCII,
 * which the atlas always holds, so it needs no extra glyphs. */
typedef enum { SL_LANG_ZH = 0, SL_LANG_EN, SL_LANG_COUNT } sl_lang_t;
extern volatile sl_lang_t sl_lang;
/* Picks the string for the current language; both stay literals, so tools/gen_glyphs.py sees them. */
#define SL_TR(zh, en) (sl_lang == SL_LANG_EN ? (en) : (zh))

typedef struct {
    uint32_t cp;
    uint8_t font;
    int8_t ox, oy; /* bitmap top-left relative to the pen on the baseline */
    uint8_t w, h, adv;
    uint32_t off;
} sl_glyph_t;

extern const sl_glyph_t sl_glyphs[];
extern const int sl_glyph_count;
extern const uint8_t sl_glyph_a8[];
/* Common-character extension (22 px only, 4 bits per pixel), for text that is not in the source,
 * such as AI-written comments. Looked up when the main atlas lacks a character. */
extern const sl_glyph_t sl_glyphs_ext[];
extern const int sl_glyph_ext_count;
extern const uint8_t sl_glyph_a4[];

/* Draws up to max_chars code points (max_chars < 0: all). Returns the number of code points in the string. */
int sl_text_draw(sg_canvas_t *cv, const char *utf8, float x, float baseline, sl_font_t font, sg_rgb_t c, int max_chars);
int sl_text_count(const char *utf8);
/* Advance width in pixels (missing glyphs count as 10). */
int sl_text_width(const char *utf8, sl_font_t font);
/* Number of glyphs missing from the atlas (for tests). */
int sl_text_missing(const char *utf8, sl_font_t font);

#ifdef __cplusplus
}
#endif
